### PR TITLE
Switch default Julia version from 1.6 to 1.8

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Review by benlorenz — COMMENTED** [review]
Thanks for starting this!
Most of the changes to the yml files are not really needed, the first job in these files can run with any julia version that is supported by OscarDevTools and is only used to prepare the matrix for the second job.
Also I would like to keep at least some jobs with the old version, I will push a few further changes very soon.

**Comment by fingolfin** [comment]
Since we are gearing up to release versions of AA and Nemo that are not compatible with Oscar 0.12.0, I think we'll overall get more useful testing by merging this right now, and improving later on.

**Comment by benlorenz** [comment]
Ok, lets see what happens.
I will merge and trigger a release later tonight once some of the tests are done.

In general we need some place / some way to write explicitly which versions are valid for the doctests. This means: package, version, Julia version.

Currently we have:
- Oscar: 
  - until 0.12.0: julia 1.6
  - starting from current 0.12.1-DEV: julia 1.8-1.10
- for everything else we know that it did work with 1.6 until now, apart from that:
  - Nemo+Hecke "should be good with 1.8" (for whatever versions that holds)

Merging this now will probably break the `Oscar#release` doctests where the checks in the yml have not been adjusted yet. (And skip the doctests where this has been done instead of the master)

I wanted to change that check in the yml to a check in jl code that is inserted into the `doctest` command, something like `include("version_check_helpers.jl"); maybe_doctest("$pkgname")`.
But I guess I descended to deep into that version mixing rabbithole.

**Comment by fingolfin** [comment]
Thank you for working on this, @benlorenz, much appreciated!

We've already changed the AA, Nemo, GAP.jl, Singular.jl doctests to run in Julia 1.8; next should take care of Hecke (or perhaps @thofma already did, I haven't checked), and perhaps also Polymake.jl (? dunno if there is need). And then of course make releases of them all with those changes. That's already done for Nemo and GAP.jl, and I think @thofma is about to make a new AA release with this. I figure we'll quickly get to the state where all packages allow running doctests with Julia 1.8, in both release and dev versions.

Of course it might still be useful to think about handling this better in the future, just in case we need to switch the doctest Julia version again in the future. But for now, just updating our packages seems to require the least amount of work overall.

**Comment by thofma** [comment]
Hecke has been using 1.8 for doctests for some time now. AA release is on the horizon.

**Pull request merged**
